// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: albums.sql

package db

import (
	"context"
	"time"

	"api/internal/domain/albums/albumtypes"
	"github.com/google/uuid"
)

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO albums (user_id, title, slug, atlas, access, date_at)
SELECT u.id, $1, $2, $3, $4, $5
FROM users u
WHERE u.id = $6 AND u.deleted_at IS NULL
RETURNING id, title, date_at, atlas, access, slug, is_active, user_id, created_at, updated_at, deleted_at
`

type CreateAlbumParams struct {
	Title  string            `json:"title"`
	Slug   string            `json:"slug"`
	Atlas  albumtypes.Atlas  `json:"atlas"`
	Access albumtypes.Access `json:"access"`
	DateAt time.Time         `json:"date_at"`
	UserID uuid.UUID         `json:"user_id"`
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, createAlbum,
		arg.Title,
		arg.Slug,
		arg.Atlas,
		arg.Access,
		arg.DateAt,
		arg.UserID,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.DateAt,
		&i.Atlas,
		&i.Access,
		&i.Slug,
		&i.IsActive,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAvailableAlbum = `-- name: GetAvailableAlbum :one
SELECT a.id, a.title, a.date_at, a.atlas, a.access, a.slug, a.is_active, a.user_id, a.created_at, a.updated_at, a.deleted_at
FROM albums a
JOIN users u ON a.user_id = u.id
WHERE u.slug = $1 AND a.slug = $2 AND a.is_active AND a.deleted_at IS NULL
`

type GetAvailableAlbumParams struct {
	UserSlug  string `json:"user_slug"`
	AlbumSlug string `json:"album_slug"`
}

type GetAvailableAlbumRow struct {
	Album Album `json:"album"`
}

func (q *Queries) GetAvailableAlbum(ctx context.Context, arg GetAvailableAlbumParams) (GetAvailableAlbumRow, error) {
	row := q.db.QueryRow(ctx, getAvailableAlbum, arg.UserSlug, arg.AlbumSlug)
	var i GetAvailableAlbumRow
	err := row.Scan(
		&i.Album.ID,
		&i.Album.Title,
		&i.Album.DateAt,
		&i.Album.Atlas,
		&i.Album.Access,
		&i.Album.Slug,
		&i.Album.IsActive,
		&i.Album.UserID,
		&i.Album.CreatedAt,
		&i.Album.UpdatedAt,
		&i.Album.DeletedAt,
	)
	return i, err
}

const hardDeleteAlbum = `-- name: HardDeleteAlbum :one
DELETE FROM albums a
USING users u
WHERE a.user_id = u.id
  AND a.id = $1
  AND a.user_id = $2
  AND a.deleted_at IS NOT NULL
  AND u.deleted_at IS NULL
RETURNING a.id
`

type HardDeleteAlbumParams struct {
	AlbumID uuid.UUID `json:"album_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) HardDeleteAlbum(ctx context.Context, arg HardDeleteAlbumParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, hardDeleteAlbum, arg.AlbumID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listAvailableAlbums = `-- name: ListAvailableAlbums :many
SELECT id, date_at, is_active, title, slug, access
FROM albums
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY date_at DESC
`

type ListAvailableAlbumsRow struct {
	ID       uuid.UUID         `json:"id"`
	DateAt   time.Time         `json:"date_at"`
	IsActive bool              `json:"is_active"`
	Title    string            `json:"title"`
	Slug     string            `json:"slug"`
	Access   albumtypes.Access `json:"access"`
}

func (q *Queries) ListAvailableAlbums(ctx context.Context, userID uuid.UUID) ([]ListAvailableAlbumsRow, error) {
	rows, err := q.db.Query(ctx, listAvailableAlbums, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAvailableAlbumsRow
	for rows.Next() {
		var i ListAvailableAlbumsRow
		if err := rows.Scan(
			&i.ID,
			&i.DateAt,
			&i.IsActive,
			&i.Title,
			&i.Slug,
			&i.Access,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedAlbums = `-- name: ListDeletedAlbums :many
SELECT id, date_at, is_active, title, slug, access
FROM albums
WHERE user_id = $1 AND deleted_at IS NOT NULL
ORDER BY date_at DESC
`

type ListDeletedAlbumsRow struct {
	ID       uuid.UUID         `json:"id"`
	DateAt   time.Time         `json:"date_at"`
	IsActive bool              `json:"is_active"`
	Title    string            `json:"title"`
	Slug     string            `json:"slug"`
	Access   albumtypes.Access `json:"access"`
}

func (q *Queries) ListDeletedAlbums(ctx context.Context, userID uuid.UUID) ([]ListDeletedAlbumsRow, error) {
	rows, err := q.db.Query(ctx, listDeletedAlbums, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeletedAlbumsRow
	for rows.Next() {
		var i ListDeletedAlbumsRow
		if err := rows.Scan(
			&i.ID,
			&i.DateAt,
			&i.IsActive,
			&i.Title,
			&i.Slug,
			&i.Access,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreAlbum = `-- name: RestoreAlbum :one
UPDATE albums a
SET
  deleted_at = NULL,
  updated_at = NOW(),
  slug = CASE
    WHEN EXISTS (
      SELECT 1 FROM albums AS a_active
      WHERE a_active.user_id = a.user_id
        AND a_active.slug = a.slug
        AND a_active.deleted_at IS NULL
        AND a_active.id != a.id
    )
    THEN left(a.slug, 246) || '-' || substring(md5(random()::text) from 1 for 8)
    ELSE a.slug
  END
FROM users u
WHERE a.user_id = u.id
  AND a.id = $1
  AND a.user_id = $2
  AND a.deleted_at IS NOT NULL
  AND u.deleted_at IS NULL
RETURNING a.id
`

type RestoreAlbumParams struct {
	AlbumID uuid.UUID `json:"album_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) RestoreAlbum(ctx context.Context, arg RestoreAlbumParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, restoreAlbum, arg.AlbumID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const softDeleteAlbum = `-- name: SoftDeleteAlbum :one
WITH old_data AS (
  SELECT a.id, u.slug AS user_slug
  FROM albums a
  JOIN users u ON a.user_id = u.id
  WHERE a.id = $1 AND a.user_id = $2 AND a.deleted_at IS NULL AND u.deleted_at IS NULL
  FOR UPDATE OF a
)
UPDATE albums
SET deleted_at = NOW(), updated_at = NOW()
FROM old_data
WHERE albums.id = old_data.id
RETURNING albums.id, albums.title, albums.date_at, albums.atlas, albums.access, albums.slug, albums.is_active, albums.user_id, albums.created_at, albums.updated_at, albums.deleted_at, old_data.user_slug
`

type SoftDeleteAlbumParams struct {
	AlbumID uuid.UUID `json:"album_id"`
	UserID  uuid.UUID `json:"user_id"`
}

type SoftDeleteAlbumRow struct {
	Album    Album  `json:"album"`
	UserSlug string `json:"user_slug"`
}

func (q *Queries) SoftDeleteAlbum(ctx context.Context, arg SoftDeleteAlbumParams) (SoftDeleteAlbumRow, error) {
	row := q.db.QueryRow(ctx, softDeleteAlbum, arg.AlbumID, arg.UserID)
	var i SoftDeleteAlbumRow
	err := row.Scan(
		&i.Album.ID,
		&i.Album.Title,
		&i.Album.DateAt,
		&i.Album.Atlas,
		&i.Album.Access,
		&i.Album.Slug,
		&i.Album.IsActive,
		&i.Album.UserID,
		&i.Album.CreatedAt,
		&i.Album.UpdatedAt,
		&i.Album.DeletedAt,
		&i.UserSlug,
	)
	return i, err
}

const softDeleteAllAlbums = `-- name: SoftDeleteAllAlbums :many
UPDATE albums a
SET deleted_at = NOW(), updated_at = NOW()
FROM users u
WHERE a.user_id = u.id
  AND a.user_id = $1
  AND a.deleted_at IS NULL
  AND u.deleted_at IS NULL
RETURNING a.id
`

func (q *Queries) SoftDeleteAllAlbums(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, softDeleteAllAlbums, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlbum = `-- name: UpdateAlbum :one
WITH old_data AS (
  SELECT a.id, a.slug AS old_slug, u.slug AS user_slug
  FROM albums a
  JOIN users u ON a.user_id = u.id
  WHERE a.id = $7 AND a.user_id = $8 AND a.deleted_at IS NULL AND u.deleted_at IS NULL
  FOR UPDATE OF a
)
UPDATE albums
SET
  title = $1,
  slug = $2,
  atlas = $3,
  access = $4,
  date_at = $5,
  is_active = $6,
  updated_at = NOW()
FROM old_data
WHERE albums.id = old_data.id
RETURNING albums.id, albums.title, albums.date_at, albums.atlas, albums.access, albums.slug, albums.is_active, albums.user_id, albums.created_at, albums.updated_at, albums.deleted_at, old_data.old_slug, old_data.user_slug
`

type UpdateAlbumParams struct {
	Title    string            `json:"title"`
	Slug     string            `json:"slug"`
	Atlas    albumtypes.Atlas  `json:"atlas"`
	Access   albumtypes.Access `json:"access"`
	DateAt   time.Time         `json:"date_at"`
	IsActive bool              `json:"is_active"`
	AlbumID  uuid.UUID         `json:"album_id"`
	UserID   uuid.UUID         `json:"user_id"`
}

type UpdateAlbumRow struct {
	Album    Album  `json:"album"`
	OldSlug  string `json:"old_slug"`
	UserSlug string `json:"user_slug"`
}

func (q *Queries) UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) (UpdateAlbumRow, error) {
	row := q.db.QueryRow(ctx, updateAlbum,
		arg.Title,
		arg.Slug,
		arg.Atlas,
		arg.Access,
		arg.DateAt,
		arg.IsActive,
		arg.AlbumID,
		arg.UserID,
	)
	var i UpdateAlbumRow
	err := row.Scan(
		&i.Album.ID,
		&i.Album.Title,
		&i.Album.DateAt,
		&i.Album.Atlas,
		&i.Album.Access,
		&i.Album.Slug,
		&i.Album.IsActive,
		&i.Album.UserID,
		&i.Album.CreatedAt,
		&i.Album.UpdatedAt,
		&i.Album.DeletedAt,
		&i.OldSlug,
		&i.UserSlug,
	)
	return i, err
}
