// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

type Querier interface {
	CleanupRefreshTokens(ctx context.Context) error
	ConsumeOtherRefreshTokensForUser(ctx context.Context, arg ConsumeOtherRefreshTokensForUserParams) error
	ConsumeRefreshTokenByHash(ctx context.Context, tokenHash string) (pgconn.CommandTag, error)
	CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (uuid.UUID, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllRefreshTokensForUser(ctx context.Context, userID uuid.UUID) error
	GetAvailableAlbum(ctx context.Context, arg GetAvailableAlbumParams) (GetAvailableAlbumRow, error)
	GetAvailableUser(ctx context.Context, id uuid.UUID) (User, error)
	GetAvailableUserBySlug(ctx context.Context, slug string) (User, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	HardDeleteAlbum(ctx context.Context, arg HardDeleteAlbumParams) (uuid.UUID, error)
	HardDeleteUser(ctx context.Context, userID uuid.UUID) (uuid.UUID, error)
	ListAvailableAlbums(ctx context.Context, userID uuid.UUID) ([]ListAvailableAlbumsRow, error)
	ListDeletedAlbums(ctx context.Context, userID uuid.UUID) ([]ListDeletedAlbumsRow, error)
	RestoreAlbum(ctx context.Context, arg RestoreAlbumParams) (uuid.UUID, error)
	RestoreUser(ctx context.Context, userID uuid.UUID) (RestoreUserRow, error)
	SoftDeleteAlbum(ctx context.Context, arg SoftDeleteAlbumParams) (SoftDeleteAlbumRow, error)
	SoftDeleteAllAlbums(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error)
	SoftDeleteUser(ctx context.Context, userID uuid.UUID) (uuid.UUID, error)
	UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) (UpdateAlbumRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
