// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const cleanupRefreshTokens = `-- name: CleanupRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at < NOW()
   OR (is_consumed = true AND updated_at < NOW() - INTERVAL '24 hours')
`

func (q *Queries) CleanupRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupRefreshTokens)
	return err
}

const consumeOtherRefreshTokensForUser = `-- name: ConsumeOtherRefreshTokensForUser :exec
UPDATE refresh_tokens
SET is_consumed = true, updated_at = NOW()
WHERE user_id = $1 AND token_hash != $2 AND is_consumed = false
`

type ConsumeOtherRefreshTokensForUserParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
}

func (q *Queries) ConsumeOtherRefreshTokensForUser(ctx context.Context, arg ConsumeOtherRefreshTokensForUserParams) error {
	_, err := q.db.Exec(ctx, consumeOtherRefreshTokensForUser, arg.UserID, arg.TokenHash)
	return err
}

const consumeRefreshTokenByHash = `-- name: ConsumeRefreshTokenByHash :execresult
UPDATE refresh_tokens
SET is_consumed = true, updated_at = NOW()
WHERE token_hash = $1 AND is_consumed = false
`

func (q *Queries) ConsumeRefreshTokenByHash(ctx context.Context, tokenHash string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, consumeRefreshTokenByHash, tokenHash)
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at, ip, ua, device, os, browser, location)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	Ip        string    `json:"ip"`
	Ua        string    `json:"ua"`
	Device    string    `json:"device"`
	Os        string    `json:"os"`
	Browser   string    `json:"browser"`
	Location  string    `json:"location"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Ip,
		arg.Ua,
		arg.Device,
		arg.Os,
		arg.Browser,
		arg.Location,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteAllRefreshTokensForUser = `-- name: DeleteAllRefreshTokensForUser :exec
DELETE FROM refresh_tokens WHERE user_id = $1
`

func (q *Queries) DeleteAllRefreshTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllRefreshTokensForUser, userID)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, is_consumed, ip, ua, device, os, browser, location, updated_at, expires_at, created_at FROM refresh_tokens
WHERE token_hash = $1
LIMIT 1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.IsConsumed,
		&i.Ip,
		&i.Ua,
		&i.Device,
		&i.Os,
		&i.Browser,
		&i.Location,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
